### ISSUE TITLE
PHP Version selection

### ISSUE THREAD

**Issue by bartkleinreesink** [Mixd/PackerWP#11]
I am currently trying to set up the script to run on our production server, however, the command line version of PHP is not compatible with the composer packages used, so I needed to select the PHP version manually.

It's probably a good idea to make an optional config option to select the PHP binary per environment.

Our production server is running DirectAdmin which supports multiple PHP versions to be installed and used on a per user basis. However, for the command line, the first version in the list will always be used, not the one connected to the user. The user I'm trying this on is on PHP 7.2 and the first version of our server is 7.0. We can't change this first version because of the possibility of breaking a lot of websites which we would then have to fix manually.

My problem was solved by adding this, but I'm sure there is a nicer implementation to be thought of:

```php
if($stage == 'production') {
  set('bin/php', function () {
    return '/usr/local/bin/php74';
  });
}
```

**Comment by DrizzlyOwl** [comment]
On your server, do you have the correct PHP binary in your user's $PATH?

**Comment by bartkleinreesink** [comment]
Deploying works for the most part using my snippet, but I still have the issue where wp-cli uses a different PHP version that causes some errors. This is due to DirectAdmin's PHP version settings. wp-cli uses the first PHP in the list. Which in my case is PHP 7.0.
