### ISSUE TITLE
running setup-local-wp gives an incorrect success message if the database already exists

### ISSUE THREAD

**Issue by roryashfordbentley** [Mixd/PackerWP#16]
If you have already migrated a database locally and you run `dep setup-local-wp` you get a message similar to this:

```
=========================================================================
WordPress has successfully been installed. Here are your login details:
Username:       xxx
Password:       xxxxxx
Email address:  xxx@xxx.co.uk
Log in at:      https://xxx.local/wordpress/wp-admin
=========================================================================
```

Hover the above message is innacurate because the username and password above dont actually get setup instead Packer appears to use the previously defined user account credentials and doent create the above account. In my isntance the account created already existed so perhaps that narrows it down a little.

**Comment by DrizzlyOwl** [comment]
This has already been considered for the next release and is patched in the `master` branch
https://github.com/Mixd/PackerWP/blob/master/config/tasks/wp.php#L26-L39

Issue to be closed at next release
