### ISSUE TITLE
HTTP user not compatible with all environments

### ISSUE THREAD

**Issue by bartkleinreesink** [Mixd/PackerWP#8]
These values were not working on my server because the user didn't exists. I changed the values to `` `whoami` `` which fixed my issue and seems to be multi applicable.

Perhaps getting these values from the config would be a nice addition.

https://github.com/Mixd/PackerWP/blob/d9980aaaf671573bf20c5117afcc17266837e53d/deploy.php#L128-L129

**Comment by DrizzlyOwl** [comment]
I understand your predicament though arguably using `whoami` would not be relevant in a use-case such as ours where we have the web server running as a different user to the deployment. Perhaps this could be an environment variable instead.

**Comment by DrizzlyOwl** [comment]
I wanted to programatically determine what user the web server was running as and it turns out that apache2 has an `envvars` file specifically for this purpose.

It's not been tested yet but here's what I cooked up.
```php
// Set apache config options
set('http_user', function () {
   if ($webuser = run("cat /etc/apache2/envvars | grep 'APACHE_RUN_USER'")) {
       $www = explode("=", $webuser);
       return end($www);
   }
   return 'www-data';
});
set('http_group', function () {
    if ($webgroup = run("cat /etc/apache2/envvars | grep 'APACHE_RUN_GROUP'")) {
        $www = explode("=", $webgroup);
        return end($www);
    }
    return 'www-data';
});
```

**Comment by bartkleinreesink** [comment]
I like your suggestion, however, I'm on nginx so this does not apply to my situation.

**Comment by DrizzlyOwl** [comment]
Do you know of a programmatic way to determine what user nginx is running as?
